# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 04:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceForms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_name', models.CharField(max_length=256, unique=True, verbose_name='Insurance Form Name')),
                ('text_fields', models.IntegerField(blank=True, default=1, null=True, verbose_name='Number Of Text Field')),
                ('label', models.CharField(blank=True, max_length=256, null=True, verbose_name='Label')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
        ),
    ]
