# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_flexible_database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceforms',
            name='check_box',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number Of Check Box Field'),
        ),
        migrations.AddField(
            model_name='insuranceforms',
            name='check_box_label',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Check Box Label'),
        ),
        migrations.AddField(
            model_name='insuranceforms',
            name='choice_field',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number Of Choice Field'),
        ),
        migrations.AddField(
            model_name='insuranceforms',
            name='choice_label',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Choice Field Label'),
        ),
        migrations.AddField(
            model_name='insuranceforms',
            name='date_field',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number Of Date Field'),
        ),
        migrations.AddField(
            model_name='insuranceforms',
            name='date_field_label',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Date Field Label'),
        ),
        migrations.AddField(
            model_name='insuranceforms',
            name='image_field',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number Of Image Field'),
        ),
        migrations.AddField(
            model_name='insuranceforms',
            name='image_field_label',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Image Field Label'),
        ),
        migrations.AddField(
            model_name='insuranceforms',
            name='radio_button',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number Of Radio Buttons Field'),
        ),
        migrations.AddField(
            model_name='insuranceforms',
            name='radio_button_label',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Radio Bouton Level'),
        ),
        migrations.AlterField(
            model_name='insuranceforms',
            name='text_fields',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Number Of Text Field'),
        ),
    ]
